language: csharp
solution: Ant.sln
mono: latest
sudo: required
branches:
  only:
    - master
script:
  - nuget restore Ant.sln
  - msbuild /p:Configuration=Release Ant.sln
  - mono ./packages/xunit.runner.console*/tools/net452/xunit.console.exe ./AntNet45Tests/bin/Release/*Tests.dll
  - nuget pack ./AntNet45/*.nuspec
